steps:

#clone a fork of Micrososft's sample arm templates
- script: git clone 'https://github.com/Azure/azure-quickstart-templates.git'
  name: cloneAppFromGitHub
  displayName: 'git clone https://github.com/Azure/azure-quickstart-templates.git'

#publish the pipeline artifact
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'infrastructure'
    targetPath: 'azure-quickstart-templates/101-webapp-basic-windows/'
